server:
  port: 8079
  servlet:
    context-path: /api
spring:
  application:
    name: lyalencar-rev-jpa
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update # em prod use: validate
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:5051/demo-spring-jpa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: appuser
    password: 123456
